### ISSUE TITLE
Support React Native 0.13

### ISSUE THREAD

**Issue by hzalaz** [auth0/Lock.ReactNative#9]
Check the new way to include it without CP: https://github.com/facebook/react-native/releases/tag/v0.13.0.

**Comment by cancan101** [comment]
Any ETA on getting a working Lock for new versions of React Native?

**Comment by hzalaz** [comment]
We are already working on this. It shouldn't take long but I don't have an ETA, probably next week

**Comment by hzalaz** [comment]
Created a different lib https://github.com/auth0/react-native-lock-ios
